name: Powershell Test
on:
 push:
  branches: [main]
  paths:
   - 'Bicep/**.bicep'
 workflow_dispatch:
 
jobs:
 build:
  name: Snyk IaC scan
  runs-on: windows-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v2
   - name: Run Script
     run: ./test.ps1
