name: Powershell Test
on:
 push:
  branches: [main]
  paths:
   - 'Bicep/**.bicep'
 workflow_dispatch:
 
jobs:
 build:
  name: Snyk IaC scan
  runs-on: self-hosted
  
  steps:
   - name: Checkout
     uses: actions/checkout@v2
   - name: Remove Test
     run: ./remove.ps1
   - name: Compile Test
     run: ./compile.ps1
   - name: Show PS version Test
     run: ./psversion.ps1
