name: Windows PowerShell
on:
    push:
      branches: [main]
      paths:
          - 'Bicep/*'
    workflow_dispatch:  
    
jobs:
    build:
      name: Run Script
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        - name: Test Script
          working-directory: ./!build
          run: ./test.ps1
          shell: powershell
