name: Powershell Test
on:
 push:
  branches: [main]
  paths:
   - 'Bicep/**.bicep'
 workflow_dispatch:
 
jobs:
 build:
  name: Snyk IaC scan
  runs-on: self-hosted
  
  steps:
   - name: Checkout
     uses: actions/checkout@v2
   - name: Compile Bicep to ARM
     run: ./test3.ps1
   - name: Run Snyk IaC scan
     run: ./test2.ps1
   - name: Commit and Push Changes
     run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Remove files using GitHub Actions"
        git push
