name: Delete files
on:
  workflow_dispatch:

jobs:
 delete-files:
  runs-on: windows-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Delete files
      run: ./test.ps1
